#ques 1
f=open('test.txt','r')
data=f.read()
print(data)
#ques 2
f=open('test.txt')
data=f.read()
j=input("Enter the element to count")
g=data.count(j)
print(j,"occurs ",g,"Times in the file")
#ques 3
f=open('test.txt')
j=open('test1.txt','a+')
data=f.read()
j.write(data)
j.seek(0)
m=j.read()
print(m)
# # ques 4
f=open('test.txt')
g=open('test2.txt')
j=open('newdoc.txt','w+')
data=f.readlines()
l=g.readlines()
for i,q in zip(data,l):
    j.write(str(i))
    j.write(str(q))
j.seek(0)
y=j.read()
print(y)
#ques 5
f=open('test.txt')
t=open('file.txt','w+')
data=f.readlines()
data.sort()
t.write(str(data))
t.seek(0)
o=t.read()
print(o)
